// Auto-generated by LibreLane
module SE_term(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  output[3:0] N_GBUF_BEG,
  output[3:0] W_GBUF_FEED_BEG,
  input[3:0] E_GBUF_END,
  input[31:0] FrameData,
  output[31:0] FrameData_O,
  input[19:0] FrameStrobe,
  output[19:0] FrameStrobe_O
);
endmodule
